POST localhost:8080/api/users/userId/recipes
Content-Type: application/json

{
  "name": "Salat 11",
  "mealType": "LUNCH",
  "source": "GU",
  "image": "BigMacSalat.jpg",
  "ingredients": [{
    "id": "1",
    "name": "Brot",
    "quantity": "1",
    "unit": "KLEIN",
    "productCategory": "BREAD_BAKERY",
    "isInShoppingList": true
  }],
  "prepTime": "30 min.",
  "preparation": "Anweisungen eintragen",
  "portions": 2,
  "favorite": false,
  "dishTypeCategory": "FISH",
  "recipeCategory": "LOW_CARB",
  "menuCategory": "MAIN_COURSE",
  "garnish": "Salat"
}